# Generated by Django 3.2.19 on 2023-06-11 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaltraining',
            options={'ordering': ('date_time',)},
        ),
        migrations.RemoveField(
            model_name='personaltraining',
            name='user_id',
        ),
        migrations.AddField(
            model_name='personaltraining',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
